.TH TELLITTO 8
.SH NAME
tellitto \- notify people via pager SMS etc.
.SH SYNOPSIS
.B tellitto
.IR [ "-f cfgfile" ]
.I person ...
.SH DESCRIPTION
Attempt to notify someone.
.PP
Controlled by the config file specified with the
.I -f
option (default
.IR /etc/tellitto/tellitto.cfg )
which says which commands, in which order, to try until one works (or
more accurately, doesn't claim to fail).
.PP
So, for example,
one can try an SNPP server, but if you can't get there,
you can connect to an SMS provider, or fall back to mail if
all else fails.
Or even send a fax.
.SH "SEE ALSO"
https://github.com/syonex/tellitto
.SH BUGS
This man page could be better.
.SH AUTHOR
John Sellens, info@syonex.com
.br
while at FreshBooks www.freshbooks.com
